### ISSUE TITLE
Runtime issue

### ISSUE THREAD

**Issue by JStyle21** [h3x0crypt/FindMyAss#3]
Hi,

I'm not sure if it's a dependency issue or a tool issue but this is what i get:

```
./ Gathering WHOIS data ...
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "FindMyAss.py", line 287, in <module>
    main()
  File "FindMyAss.py", line 262, in main
    is_valid_domain,status,whois_resp = fetchWhoisData(domain)
TypeError: cannot unpack non-iterable NoneType object

```

**Comment by h3x0crypt** [comment]
sad to say that but HostSpider Tool no more supported and no longer works
